// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Blog is the predicate function for blog builders.
type Blog func(*sql.Selector)

// Cate is the predicate function for cate builders.
type Cate func(*sql.Selector)

// Comment is the predicate function for comment builders.
type Comment func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
