// Code generated by ent, DO NOT EDIT.

package runtime

import (
	"restent/ent/blog"
	"restent/ent/cate"
	"restent/ent/comment"
	"restent/ent/schema"
	"restent/ent/user"
	"time"

	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	blogMixin := schema.Blog{}.Mixin()
	blogMixinFields0 := blogMixin[0].Fields()
	_ = blogMixinFields0
	blogMixinFields1 := blogMixin[1].Fields()
	_ = blogMixinFields1
	blogFields := schema.Blog{}.Fields()
	_ = blogFields
	// blogDescCreatedAt is the schema descriptor for created_at field.
	blogDescCreatedAt := blogMixinFields0[0].Descriptor()
	// blog.DefaultCreatedAt holds the default value on creation for the created_at field.
	blog.DefaultCreatedAt = blogDescCreatedAt.Default.(func() time.Time)
	// blogDescUpdatedAt is the schema descriptor for updated_at field.
	blogDescUpdatedAt := blogMixinFields0[1].Descriptor()
	// blog.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	blog.UpdateDefaultUpdatedAt = blogDescUpdatedAt.UpdateDefault.(func() time.Time)
	// blogDescID is the schema descriptor for id field.
	blogDescID := blogMixinFields1[0].Descriptor()
	// blog.DefaultID holds the default value on creation for the id field.
	blog.DefaultID = blogDescID.Default.(func() uuid.UUID)
	cateMixin := schema.Cate{}.Mixin()
	cateMixinFields0 := cateMixin[0].Fields()
	_ = cateMixinFields0
	cateMixinFields1 := cateMixin[1].Fields()
	_ = cateMixinFields1
	cateFields := schema.Cate{}.Fields()
	_ = cateFields
	// cateDescCreatedAt is the schema descriptor for created_at field.
	cateDescCreatedAt := cateMixinFields0[0].Descriptor()
	// cate.DefaultCreatedAt holds the default value on creation for the created_at field.
	cate.DefaultCreatedAt = cateDescCreatedAt.Default.(func() time.Time)
	// cateDescUpdatedAt is the schema descriptor for updated_at field.
	cateDescUpdatedAt := cateMixinFields0[1].Descriptor()
	// cate.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	cate.UpdateDefaultUpdatedAt = cateDescUpdatedAt.UpdateDefault.(func() time.Time)
	// cateDescID is the schema descriptor for id field.
	cateDescID := cateMixinFields1[0].Descriptor()
	// cate.DefaultID holds the default value on creation for the id field.
	cate.DefaultID = cateDescID.Default.(func() uuid.UUID)
	commentMixin := schema.Comment{}.Mixin()
	commentMixinFields0 := commentMixin[0].Fields()
	_ = commentMixinFields0
	commentMixinFields1 := commentMixin[1].Fields()
	_ = commentMixinFields1
	commentFields := schema.Comment{}.Fields()
	_ = commentFields
	// commentDescCreatedAt is the schema descriptor for created_at field.
	commentDescCreatedAt := commentMixinFields0[0].Descriptor()
	// comment.DefaultCreatedAt holds the default value on creation for the created_at field.
	comment.DefaultCreatedAt = commentDescCreatedAt.Default.(func() time.Time)
	// commentDescUpdatedAt is the schema descriptor for updated_at field.
	commentDescUpdatedAt := commentMixinFields0[1].Descriptor()
	// comment.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	comment.UpdateDefaultUpdatedAt = commentDescUpdatedAt.UpdateDefault.(func() time.Time)
	// commentDescID is the schema descriptor for id field.
	commentDescID := commentMixinFields1[0].Descriptor()
	// comment.DefaultID holds the default value on creation for the id field.
	comment.DefaultID = commentDescID.Default.(func() uuid.UUID)
	userMixin := schema.User{}.Mixin()
	userHooks := schema.User{}.Hooks()
	user.Hooks[0] = userHooks[0]
	userMixinFields0 := userMixin[0].Fields()
	_ = userMixinFields0
	userMixinFields1 := userMixin[1].Fields()
	_ = userMixinFields1
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userMixinFields0[0].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userMixinFields0[1].Descriptor()
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
	// userDescName is the schema descriptor for name field.
	userDescName := userFields[2].Descriptor()
	// user.DefaultName holds the default value on creation for the name field.
	user.DefaultName = userDescName.Default.(string)
	// userDescID is the schema descriptor for id field.
	userDescID := userMixinFields1[0].Descriptor()
	// user.DefaultID holds the default value on creation for the id field.
	user.DefaultID = userDescID.Default.(func() uuid.UUID)
}

const (
	Version = "v0.11.2"                                         // Version of ent codegen.
	Sum     = "h1:UM2/BUhF2FfsxPHRxLjQbhqJNaDdVlOwNIAMLs2jyto=" // Sum of ent codegen.
)
